server:
    path: /api-docs
    enabled: true
  api-docs:
    enabled: true
    path: /swagger-ui.html
  swagger-ui:
springdoc:
# Configuraci√≥n de SpringDoc OpenAPI

        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
    properties:
    show-sql: true
      ddl-auto: update
    hibernate:
  jpa:

    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/powerup_dev
  datasource:
spring:

  port: 8081

